server:
  port: 8080
  
awsregion: us-east-1

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DB_URL}:${port}/${database}?useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true